# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jean Melo
tagline:          Website
description:      "phd in cs & softw dev"
url:              https://github.com/jccmelo
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Jean Melo
  url:            https://twitter.com/jccmelo

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0

github:
  repo:             https://github.com/jccmelo
