# Dependencies
markdown:         kramdown
highlighter:      rouge

# Google Analytics
google_analytics: UA-42794425-3

# Setup
title:            Jean Melo
tagline:          Website
description:      "phd in cs | softw engineer"
url:              https://jccmelo.com   # with the https protocol
enforce_ssl:      jccmelo.com   # without any protocol
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Jean Melo
  url:            https://twitter.com/jccmelo

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0

github:
  repo:             https://github.com/jccmelo
